#!/bin/bash
# Commands to create a file structure for notes, should only be run in a notes 
# folder, with a common module.tex file.
# .
# ├── (title)
# │   ├── code
# │   │   └── (empty)
# │   ├── image
# │   │   └── (empty)
# │   ├── diagram
# │   │   └── (empty)
# │   └── (title).tex
#
# The text file will have the normal preamble and a number of questions

# Default arguments:
user='Oliver Killane'
title='new notes'
subject='some topic'
date=$(date +'%d/%m/%y')
link='https://www.youtube.com/watch?v=dQw4w9WgXcQ'
help='
This is the newnotes tool help! 
Make latex tutorial sheet templates quick so you can get back to depression, synthwave and car exhaust!
Help if below, for the tool, if you need any other general help please consult Jeff Bezos`s Barber.
Arg:            What it do:
-h              Show this mercilessly boring help text! And ignore any other arguments.
-s <subject>    Subject of/lesson learnt from the lecture (e.g "you should go outside more")
-t <title>      Set the tutorial sheet title.
-l <link>       The link to the panopto recording for the notes.
-u <user>       Set the author name, you right? If you plagarise in your work, I will plagarise your mom.
-d <date>       Set the date, by default is the current date.
'

folder=$(basename "$PWD")

SWE='50002 - Software Engineering Design'
MOD='50003 - Models Of Computation'
OS='50004 - Operating Systems'
ALG='50001 - Algorithm Analysis and Design'
NET='50005 - Networks and Communications'
COMP='50006 - Compilers'
STAT='50008 - Probability and Statistics'


case $folder in
    $SWE | $MOD | $OS | $ALG | $NET | $COMP | $STAT);;
    *) echo "Must be in a notes folder, cannot be $folder"; exit;;
esac


while getopts hs:t:l:u:d: flag;
do
    case "${flag}" in
        h) echo "$help"; exit;;
        s) subject=${OPTARG};;
        t) title=${OPTARG};;
        l) link=${OPTARG};;
        u) user=${OPTARG};;
        d) date=${OPTARG};;
    esac
done

mkdir "$title - ($subject)";
cd "$title - ($subject)";

mkdir 'code' 'image' 'diagram';
touch "$title.tex";



echo "\documentclass{report}
    \title{$folder - $title}
    \author{$user}
    \date{$date}
\input{$(ls ../*common.tex)}
\begin{document}
    \maketitle
    \lectlink{$link}
\end{document}" > "$title.tex"

echo "Created: $folder - $title by $user. Now piss off.";
