#!/bin/bash
# Commands to create a file structure for a tutorial
# .
# ├── (title)
# │   ├── code
# │   │   └── (empty)
# │   ├── image
# │   │   └── (empty)
# │   ├── diagram
# │   │   └── (empty)
# │   └── (title).tex
#
# The text file will have the normal preamble and a number of questions

# Default arguments:
user='Oliver Killane'
tutorial='tutorial here'
module='module here'
date=$(date +'%d/%m/%y')
sections=0
help='
This is the newtut tool help! 
Make latex tutorial sheet templates quick so you can get back to depression, synthwave and car exhaust!

Help if below, for the tool, if you need any other general help please consult Jeff Bezos`s Barber.

Arg:            What it do:
-h              Show this mercilessly boring help text! And ignore any other arguments.
-t <title>      Set the tutorial sheet title.
-m <module>     Set the module of the tutorial sheet.
-s <sections>   Set the number of mains sections (questions).
-u <user>       Set the author name, you right? If you plagarise in your work, I will plagarise your mom.
-d <date>       Set the date, by default is the current date.
'


# getting aruments
while getopts ht:m:s:u:d: flag;
do
    case "${flag}" in
        h) echo "$help"; exit;;
        t) tutorial=${OPTARG};;
        m) module=${OPTARG};;
        s) sections=${OPTARG};;
        u) user=${OPTARG};;
        d) date=${OPTARG};;
    esac
done

# create directory
mkdir "$tutorial";
cd "$tutorial";

mkdir 'code' 'image' 'diagram';
touch "$tutorial.tex";

# tex file preamble
echo "\documentclass{report}
    \title{$module - $tutorial}
    \author{$user}
    \date{$date}
%====================================IMPORTS====================================
\usepackage[a4paper, total={6in, 8in}]{geometry}
\usepackage{graphicx, amssymb, amsfonts, amsmath, xcolor, listings, tcolorbox, multirow, hyperref}
%===============================================================================

%====================================IMAGES=====================================
\graphicspath{{image/}}

% \centerimage{options}{image}
\newcommand{\centerimage}[2]{\begin{center}
    \includegraphics[#1]{#2}
\end{center}}
%===============================================================================

%==============================SYNTAX HIGHLIGHTING==============================
\newcommand{\fun}[1]{\textcolor{blue}{\textbf{#1}}}
\newcommand{\file}[1]{\textcolor{green}{\textbf{#1}}}
\newcommand{\struct}[1]{\textcolor{orange}{\textbf{#1}}}
\newcommand{\var}[1]{\textcolor{purple}{\textbf{#1}}}
\newcommand{\const}[1]{\textcolor{red}{\textbf{#1}}}
%===============================================================================

%=================================CODE LISTINGS=================================
\definecolor{codebackdrop}{gray}{0.9}
\definecolor{commentgreen}{rgb}{0,0.6,0}
\lstset{
    inputpath=code, 
    commentstyle=\color{commentgreen},
    keywordstyle=\color{blue}, 
    backgroundcolor=\color{codebackdrop}, 
    basicstyle=\footnotesize,
    frame=single,
    numbers=left,
    stepnumber=1,
    showstringspaces=false,
    breaklines=true,
    postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space}
}

% Create a code listing for a single line
% \codeline{language}{line}{file}
\newcommand{\codeline}[3]{\lstinputlisting[language=#1, firstline = #2, lastline = #2]{#3}}

% Create a code listing for multiple lines
% \codeline{language}{start}{end}{file}
\newcommand{\codelines}[4]{\lstinputlisting[language=#1, firstline = #2, lastline = #3]{#4}}


% Create a code listing for a given language & file
% \codelist{language}{file}
\newcommand{\codelist}[2]{\lstinputlisting[language=#1]{#2}}
%===============================================================================

%================================TEXT STRUCTURES================================
% Marka a word as bold
% \keyword{important word}
\newcommand{\keyword}[1]{\textbf{#1}}

% Creates a section in italics
% \question{question in italics}
\newcommand{\question}[1]{\textit{#1} \\ }

% Creates a box with title for side notes.
% \sidenote{title}{contents}
\newcommand{\sidenote}[2]{\begin{tcolorbox}[title=#1]#2\end{tcolorbox}}

\newcommand{\termdef}[2]{\begin{tcolorbox}[title=Definition: #1, colframe = blue]#2\end{tcolorbox}}

% Creates an item in an itemize or enumerate, with a paragraph after
% \begin{itemize}
%     \bullpara{title}{contents}
% \end{itemize}
\newcommand{\bullpara}[2]{\item \textbf{#1} \ #2}

% Creates a compact list (very small gaps between items)
% \compitem{
%     \item item 1
%     \item item 2
%     \item ...
% }
\newcommand{\compitem}[1]{\begin{itemize}\setlength\itemsep{-0.5em}#1\end{itemize}}
\newcommand{\compenum}[1]{\begin{enumerate}\setlength\itemsep{-0.5em}#1\end{enumerate}}

% Creates a link to the lecture for use at the start of the notes document
\newcommand{\lectlink}[1]{\sidenote{Lecture Recording}{
    Lecture recording is available \href{#1}{here}
}}
%===============================================================================

%================================STYLIZED PROOFS================================
%For ease in writing stylized proofs with numbers
\newcommand{\stepno}[1]{\textcolor{red}{\textbf{#1}}}

\newenvironment{proof}
{\begin{center}\begin{tabular}{r l l }}
{\end{tabular}\end{center}}

%\proofstep{step}{workings}{description}
\newcommand{\proofstep}[3]{\stepno{(#1)} & #2 & #3 \\}
%===============================================================================

%==============================UNFINISHED SECTION===============================
\newcommand{\unfinished}{\begin{huge} \textcolor{red}{\textbf{UNFINISHED!!!}} \end{huge}}
%===============================================================================
\begin{document}
    \maketitle
" > "$tutorial.tex";

# add sections
n=0;
while [ "$n" -lt $sections ];
do 
    ((n++))
echo "    \section*{Question $n}
" >> "$tutorial.tex";
done

# add ending
echo "\end{document}" >> "$tutorial.tex";

# final output
echo "Created: $module - $tutorial by $user with $sections sections. Now fuck off.";